# Generated by Django 2.0 on 2017-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
